version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: pandora_prueba_tecnica_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../src/bd/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pandora_prueba_tecnica_network

  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: pandora_prueba_tecnica_php
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    env_file:
      - ../.env
    networks:
      - pandora_prueba_tecnica_network

volumes:
  db_data:

networks:
  pandora_prueba_tecnica_network:
    driver: bridge